/**
 * @typedef {import(".").Params} Params
 * @typedef {import(".").ParamsMather} ParamsMather
 */

const routeParameterPattern = ":([a-zA-Z0-9_]+)";
const routeParametersRegex = new RegExp(routeParameterPattern, "g");

/**
 *
 * @param {string} routePath
 * @returns {ParamsMather}
 */
const matcher = (routePath) => {
  /** @type {RegExp} */
  let _regex = null;
  /** @type {string[]} */
  let _paramNames = null;

  /**
   * Lazily computes and returns the regular expression for the route path.
   * The regex is generated by replacing parameter placeholders (e.g., ":id") with a pattern that captures the parameter value.
   * @returns {RegExp}
   */
  const getRegex = () => {
    if (!_regex) {
      const pattern = routePath.replace(routeParametersRegex, "([^/]+)");
      _regex = new RegExp(`^${pattern}$`);
    }
    return _regex;
  };

  /**
   * Lazily extracts and returns the parameter names from the route path.
   * Parameter names are identified by the pattern ":paramName" in the route path.
   * @returns {string[]}
   */
  const getParamNames = () => {
    if (!_paramNames) {
      _paramNames = (routePath.match(routeParametersRegex) || []).map((param) =>
        param.substring(1)
      );
    }
    return _paramNames;
  };

  /**
   * Checks if a given pathname matches the route pattern.
   * @param {string} pathname - The actual request pathname.
   * @returns {boolean} True if the pathname matches the route pattern, false otherwise.
   */
  const test = (pathname) => getRegex().test(pathname);

  /**
    * Extracts route parameters from a URL pathname using the route pattern.
   * @param {string} pathname 
   * @returns {RegExpMatchArray | null} The match result or null if no match.
   */
  const matches = (pathname) => pathname.match(getRegex());

  /**
   * Extracts route parameters from a URL pathname using a path pattern.
   * @param {string} pathname - The actual request pathname.
   * @returns {Params} Extracted parameters.
   */
  const extract = (pathname) => {
    /** @type {Params} */
    const params = {};

    const match = matches(pathname);

    if (!match) {
      return params;
    }

    const paramNames = getParamNames();

    paramNames.forEach((name, index) => {
      params[name] = match[index + 1];
    });
    return params;
  };

  return { test, extract };
};

module.exports = { matcher };
